#!/usr/bin/env node
/**
 * agent-architecture installer.
 *
 * Usage:
 *   node scripts/install.mjs [--private] [--target <dir>] [--hosts <list>]
 *   node scripts/install.mjs --upgrade [--private] [--target <dir>]
 *   node scripts/install.mjs --doctor [--target <dir>]
 *   node scripts/install.mjs --dry-run [--private] [--target <dir>]
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);

const PRIVATE = args.includes('--private');
const DRY_RUN = args.includes('--dry-run');
const UPGRADE = args.includes('--upgrade');
const DOCTOR = args.includes('--doctor');

const targetIdx = args.indexOf('--target');
const TARGET = targetIdx !== -1 ? path.resolve(args[targetIdx + 1]) : path.join(process.cwd(), '.agent');

const hostsIdx = args.indexOf('--hosts');
const HOSTS = hostsIdx !== -1
  ? args[hostsIdx + 1].split(',').map((h) => h.trim())
  : ['claude', 'codex', 'copilot'];

// Agents not installed in private mode by default (stripped)
const PRIVATE_STRIP_MCPS = new Set(['cavemem', 'gstack-analytics', 'gstack-update-check', 'gbrain']);

function readConfig() {
  const configPath = path.join(process.cwd(), '.agent-config.json');
  if (!fs.existsSync(configPath)) {
    return {
      private: PRIVATE,
      hosts: HOSTS,
      agents: ['swe', 'qa-agent', 'spec-agent', 'pm'],
      mcps: [],
    };
  }
  return JSON.parse(fs.readFileSync(configPath, 'utf8'));
}

function readPackageVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  return pkg.version || '0.0.0';
}

function writeFile(rel, content) {
  if (DRY_RUN) return;
  const full = path.join(TARGET, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf8');
}

function parseFrontmatter(content) {
  const text = content.charCodeAt(0) === 0xFEFF ? content.slice(1) : content;
  const normalized = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  if (!normalized.startsWith('---\n')) return {};
  const end = normalized.indexOf('\n---', 4);
  if (end === -1) return {};
  const block = normalized.slice(4, end);
  const result = {};
  const nameMatch = block.match(/^name:\s*(.+)$/m);
  if (nameMatch) result.name = nameMatch[1].trim();
  const descMatch = block.match(/^description:\s*\|?\s*\n((?:[ \t]+.+\n?)*)/m);
  if (descMatch) {
    result.description = descMatch[1].replace(/^[ \t]{2}/gm, '').trim().split('\n')[0];
  }
  return result;
}

function readAgentSkill(agentName) {
  const tmplPath = path.join(ROOT, 'agents', agentName, 'SKILL.md.tmpl');
  if (!fs.existsSync(tmplPath)) return null;
  const content = fs.readFileSync(tmplPath, 'utf8');
  // Resolve simple placeholders
  const resolved = content
    .replace(/\{\{PREAMBLE\}\}/g, [
      '## Enterprise Preamble',
      '',
      '- Stay inside the current project unless the user explicitly names another path.',
      '- Do not call public telemetry, public update checks, public tunnels, or public scraping.',
      '- Use policy-gated tools only when the active profile allows them.',
      '- Commit after each discrete behavior change.',
    ].join('\n'))
    .replace(/\{\{POLICY_REQUIREMENTS\}\}/g, [
      '## Policy Requirements',
      '',
      '- Read-only code inspection is allowed.',
      '- Shell write, git write, deployment, and database read require policy approval.',
      '- Credential reads, cookie import, public tunnels, and public telemetry are disabled.',
    ].join('\n'));
  return resolved;
}

function generateSettings(config) {
  const mcps = {};
  const activeMcps = (config.mcps || []).filter((m) => {
    if (PRIVATE && PRIVATE_STRIP_MCPS.has(m.name)) return false;
    return true;
  });
  for (const mcp of activeMcps) {
    const env = {};
    for (const envVar of mcp.credentialEnvVars || []) {
      env[envVar] = `$${envVar}`;
    }
    mcps[mcp.name] = {
      command: mcp.command,
      args: mcp.args || [],
      env,
    };
  }

  const settings = { mcpServers: mcps };
  if (PRIVATE) {
    settings.env = { CLAUDE_CODE_DISABLE_AUTO_MEMORY: '1' };
  }
  return JSON.stringify(settings, null, 2);
}

function generateClaudeMd(config, version) {
  const agents = config.agents || [];
  const lines = [
    '# CLAUDE.md — agent-architecture install',
    '',
    `> Generated by agent-architecture v${version}. Do not edit directly.`,
    '',
    '## Available Agents',
    '',
  ];
  for (const agent of agents) {
    const tmplPath = path.join(ROOT, 'agents', agent, 'SKILL.md.tmpl');
    if (fs.existsSync(tmplPath)) {
      const fm = parseFrontmatter(fs.readFileSync(tmplPath, 'utf8'));
      lines.push(`- \`/${agent}\` — ${fm.description || agent}`);
    }
  }
  lines.push('');
  lines.push('## Private Mode');
  lines.push('');
  if (PRIVATE) {
    lines.push('This install is private: no telemetry, no cloud memory, no update checks.');
  }
  lines.push('');
  lines.push('## Skill Reference');
  lines.push('');
  lines.push('Skills are installed at: `skills/<agent>/SKILL.md`');
  return lines.join('\n');
}

function generateAgentsMd(config, version) {
  const agents = config.agents || [];
  const lines = [
    '# AGENTS.md — agent-architecture install',
    '',
    `> Generated by agent-architecture v${version}. Do not edit directly.`,
    '',
    '## Available Agents',
    '',
  ];
  for (const agent of agents) {
    const tmplPath = path.join(ROOT, 'agents', agent, 'SKILL.md.tmpl');
    if (fs.existsSync(tmplPath)) {
      const fm = parseFrontmatter(fs.readFileSync(tmplPath, 'utf8'));
      lines.push(`- ${agent}: ${fm.description || agent}`);
    }
  }
  lines.push('');
  lines.push('## Safety Defaults');
  lines.push('');
  lines.push('- No public telemetry.');
  lines.push('- No credential reads without explicit configuration.');
  return lines.join('\n');
}

function generateCopilotInstructions(config, version) {
  const agents = config.agents || [];
  const lines = [
    '# GitHub Copilot Instructions — agent-architecture install',
    '',
    `> Generated by agent-architecture v${version}. Do not edit directly.`,
    '',
    '## Available Agents',
    '',
  ];
  for (const agent of agents) {
    lines.push(`- /${agent}`);
  }
  return lines.join('\n');
}

function generateManifest(config, version) {
  return JSON.stringify({
    name: 'agent-architecture',
    version,
    private: !!(config.private || PRIVATE),
    agents: config.agents || [],
    hosts: config.hosts || HOSTS,
    generatedAt: new Date().toISOString(),
  }, null, 2);
}

function installAgentSkill(agentName) {
  const content = readAgentSkill(agentName);
  if (!content) {
    console.warn(`WARN: agent "${agentName}" not found in agents/`);
    return;
  }
  writeFile(`skills/${agentName}/SKILL.md`, content);
}

function copyDirRecursive(srcDir, destRelDir) {
  if (!fs.existsSync(srcDir)) return;
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    if (entry.name === '__pycache__' || entry.name.endsWith('.pyc')) continue;
    const srcPath = path.join(srcDir, entry.name);
    const destRel = `${destRelDir}/${entry.name}`;
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destRel);
    } else {
      writeFile(destRel, fs.readFileSync(srcPath));
    }
  }
}

function installTokenOptimizer() {
  const src = path.join(ROOT, 'token-optimizer');
  if (!fs.existsSync(src)) return;
  // Copy ptk_minimize.py
  const scriptSrc = path.join(src, 'ptk_minimize.py');
  if (fs.existsSync(scriptSrc)) {
    writeFile('token-optimizer/ptk_minimize.py', fs.readFileSync(scriptSrc));
  }
  // Copy bundled lib/ptk/
  copyDirRecursive(path.join(src, 'lib'), 'token-optimizer/lib');
}

function install() {
  const config = readConfig();
  const version = readPackageVersion();
  const agents = config.agents || [];

  if (!DRY_RUN) {
    fs.mkdirSync(TARGET, { recursive: true });
  }

  // Install agent skills
  for (const agent of agents) {
    installAgentSkill(agent);
  }

  // Install token-optimizer CLI + bundled lib
  installTokenOptimizer();

  // Generate host artifacts
  const activeHosts = config.hosts || HOSTS;
  if (activeHosts.includes('claude')) {
    writeFile('CLAUDE.md', generateClaudeMd(config, version));
  }
  if (activeHosts.includes('codex')) {
    writeFile('AGENTS.md', generateAgentsMd(config, version));
  }
  if (activeHosts.includes('copilot')) {
    writeFile('copilot-instructions.md', generateCopilotInstructions(config, version));
  }

  // Settings (private mode)
  writeFile('settings.json', generateSettings(config));

  // Version file
  writeFile('VERSION', version);

  // Manifest
  writeFile('install-manifest.json', generateManifest(config, version));

  if (!DRY_RUN) {
    console.log(`agent-architecture v${version} installed to ${TARGET}`);
    console.log(`  agents: ${agents.join(', ')}`);
    console.log(`  hosts:  ${(config.hosts || HOSTS).join(', ')}`);
    if (PRIVATE) console.log('  mode:   private (no telemetry, no cloud memory)');
  }
}

function doctor() {
  const errors = [];

  // Check VERSION
  const versionPath = path.join(TARGET, 'VERSION');
  if (!fs.existsSync(versionPath)) {
    errors.push(`VERSION missing at ${TARGET}/VERSION — run install first`);
  }

  // Check manifest
  const manifestPath = path.join(TARGET, 'install-manifest.json');
  if (!fs.existsSync(manifestPath)) {
    errors.push(`install-manifest.json missing — run install first`);
  } else {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    for (const agent of (manifest.agents || [])) {
      const skillPath = path.join(TARGET, 'skills', agent, 'SKILL.md');
      if (!fs.existsSync(skillPath)) {
        errors.push(`agent "${agent}" declared in manifest but skills/${agent}/SKILL.md missing`);
      }
    }
  }

  // Check settings
  const settingsPath = path.join(TARGET, 'settings.json');
  if (!fs.existsSync(settingsPath)) {
    errors.push(`settings.json missing at ${TARGET}/settings.json`);
  }

  if (errors.length > 0) {
    for (const err of errors) console.error(`ERROR: ${err}`);
    process.exitCode = 1;
  } else {
    console.log(`doctor: OK (${TARGET})`);
  }
}

if (DOCTOR) {
  doctor();
} else {
  install();
}
